import jsPDF from "jspdf";

export const generateYearlyReportPDF = (reportData) => {
  if (!reportData) {
    console.error("No report data provided");
    return;
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Set title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Yearly Sales Report", pageWidth / 2, yPosition, { align: "center" });

  // Set company name
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("BukSu EEU", pageWidth / 2, yPosition + 10, { align: "center" });

  yPosition += 25;

  // Report Period
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Period: ${reportData.period || "N/A"}`, 20, yPosition);

  // Generation Date
  yPosition += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, yPosition);

  yPosition += 15;

  // Summary Section
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Summary", 20, yPosition);

  yPosition += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const summary = reportData.summary || {};
  const summaryData = [
    { label: "Total Revenue", value: (summary.totalRevenue || 0).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) },
    { label: "Total Orders", value: summary.totalOrders || 0 },
    { label: "Average Order Value", value: (summary.avgOrderValue || 0).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) },
    { label: "Total Items Sold", value: summary.totalItemsSold || 0 },
  ];

  summaryData.forEach((item) => {
    doc.text(`${item.label}: ${item.value}`, 20, yPosition);
    yPosition += 8;
  });

  yPosition += 10;

  // Monthly Breakdown Section
  if (reportData.monthlyBreakdown && reportData.monthlyBreakdown.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Monthly Breakdown", 20, yPosition);

    yPosition += 10;

    // Table Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("Month", 20, yPosition);
    doc.text("Revenue", 70, yPosition);
    doc.text("Orders", 120, yPosition);
    doc.text("Items", 160, yPosition);

    yPosition += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);

    // Table rows
    reportData.monthlyBreakdown.forEach((month) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
        // Re-draw header on new page
        doc.setFont("helvetica", "bold");
        doc.text("Month", 20, yPosition);
        doc.text("Revenue", 70, yPosition);
        doc.text("Orders", 120, yPosition);
        doc.text("Items", 160, yPosition);
        yPosition += 8;
        doc.setFont("helvetica", "normal");
      }

      const monthStr = month.label || "N/A";
      const revenue = month.totalSales ? month.totalSales.toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : "0.00";
      const orders = month.orderCount || 0;
      const items = month.totalItems || 0;

      doc.text(monthStr, 20, yPosition);
      doc.text(revenue, 70, yPosition);
      doc.text(orders.toString(), 120, yPosition);
      doc.text(items.toString(), 160, yPosition);

      yPosition += 8;
    });
  }

  // Footer
  yPosition = pageHeight - 15;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.text("This is an automated report generated by BukSu EEU", 20, yPosition);
  doc.text(`Page 1 of ${doc.internal.pages.length}`, pageWidth - 30, yPosition);

  // Save the PDF
  const fileName = `Yearly_Report_${reportData.period?.replace(/\s+/g, "_") || "Report"}.pdf`;
  doc.save(fileName);
};
