import jsPDF from "jspdf";

export const generateInventoryReportPDF = (reportData) => {
  if (!reportData) {
    console.error("No report data provided");
    return;
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Set title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Inventory Report", pageWidth / 2, yPosition, { align: "center" });

  // Set company name
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("BukSu EEU", pageWidth / 2, yPosition + 10, { align: "center" });

  yPosition += 25;

  // Report Period
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Period: ${reportData.period || "N/A"}`, 20, yPosition);

  // Generation Date
  yPosition += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, yPosition);

  yPosition += 15;

  // Summary Section
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Summary", 20, yPosition);

  yPosition += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const summary = reportData.summary || {};
  const summaryData = [
    { label: "Total Products", value: summary.totalProducts || 0 },
    { label: "Total Stock Value", value: parseFloat(summary.totalStockValue || 0).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) },
    { label: "Low Stock Items", value: summary.lowStockItems || 0 },
    { label: "Out of Stock", value: summary.outOfStockItems || 0 },
  ];

  summaryData.forEach((item) => {
    doc.text(`${item.label}: ${item.value}`, 20, yPosition);
    yPosition += 8;
  });

  yPosition += 10;

  // Inventory Items Section
  if (reportData.inventory && reportData.inventory.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Inventory Items", 20, yPosition);

    yPosition += 10;

    // Table Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.text("Product", 20, yPosition);
    doc.text("Stock", 70, yPosition);
    doc.text("Price", 95, yPosition);
    doc.text("Sold", 120, yPosition);
    doc.text("Revenue", 140, yPosition);

    yPosition += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);

    // Table rows
    reportData.inventory.forEach((item) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
        // Re-draw header on new page
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.text("Product", 20, yPosition);
        doc.text("Stock", 70, yPosition);
        doc.text("Price", 95, yPosition);
        doc.text("Sold", 120, yPosition);
        doc.text("Revenue", 140, yPosition);
        yPosition += 8;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
      }

      const title = item.title || "N/A";
      const stock = item.currentStock || 0;
      const price = item.price ? `${parseFloat(item.price).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : "0.00";
      const sold = item.soldQuantity || 0;
      const revenue = item.revenue ? `${parseFloat(item.revenue).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : "0.00";

      // Truncate product name if too long
      const truncatedTitle = title.length > 30 ? title.substring(0, 27) + "..." : title;

      doc.text(truncatedTitle, 20, yPosition);
      doc.text(stock.toString(), 70, yPosition);
      doc.text(price, 95, yPosition);
      doc.text(sold.toString(), 120, yPosition);
      doc.text(revenue, 140, yPosition);

      yPosition += 8;
    });
  }

  // Footer
  yPosition = pageHeight - 15;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.text("This is an automated report generated by BukSu EEU", 20, yPosition);
  doc.text(`Page 1 of ${doc.internal.pages.length}`, pageWidth - 30, yPosition);

  // Save the PDF
  const fileName = `Inventory_Report_${reportData.period?.replace(/\s+/g, "_") || "Report"}.pdf`;
  doc.save(fileName);
};
